### ISSUE TITLE
creation of basic Schema not idempotent?

### ISSUE THREAD

**Issue by krosaen** [kolypto/py-good#12]
As illustrated by this repl session:

```
$ python
Python 3.4.4 |Anaconda 2.3.0 (x86_64)| (default, Jan  9 2016, 17:30:09) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from good import Schema
>>> Schema({'a': int})({'a': 2})
{'a': 2}
>>> Schema({'a': int})({'a': 2})
Traceback (most recent call last):
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/util.py", line 92, in get_type_name
    return __type_names[t]
KeyError: <class 'int'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/__init__.py", line 280, in __init__
    extra_keys)
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/compiler.py", line 502, in _compile_mapping
    for key, value in schema.items()}
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/compiler.py", line 502, in <dictcomp>
    for key, value in schema.items()}
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/compiler.py", line 189, in sub_compile
    matcher
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/compiler.py", line 301, in _compile_type
    self.name = get_type_name(schema)
  File "/Users/krosaen/anaconda/lib/python3.4/site-packages/good/schema/util.py", line 96, in get_type_name
    return _(u'Integer number')
TypeError: 'dict' object is not callable
```

**Comment by Varriount** [comment]
I get something similar, except I get `'list' object is not callable`.

**Comment by vartagg** [comment]
Duplicates #3 #4

**Comment by kolypto** [comment]
Duplicate
