### ISSUE TITLE
Very odd issues (0.0.7_0 from pypi)

### ISSUE THREAD

**Issue by dpnova** [kolypto/py-good#3]
I've included a shell session below for you to check out. Seems like some very odd things happening..

We'd love to use this in our API.. 

```
>>> from good import Schema
>>> s = Schema({"a": str})
>>> s({"a":"meow"})
{'a': 'meow'}
>>> s({"d":"meow"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 607, in validate_mapping
    matches = key_schema.compiled.execute(d, matches)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/markers.py", line 216, in execute
    raise Invalid(self.error_message, self.name, _(u'-none-'), path)
TypeError: 'dict' object is not callable
>>> s({"d":1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 607, in validate_mapping
    matches = key_schema.compiled.execute(d, matches)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/markers.py", line 216, in execute
    raise Invalid(self.error_message, self.name, _(u'-none-'), path)
TypeError: 'dict' object is not callable
>>> s
CompiledSchema({'a': <type 'str'>}, [], Required, Reject)
>>> s()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __call__() takes exactly 2 arguments (1 given)
>>> s(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 545, in validate_mapping
    raise err_type(provided=get_type_name(type(d)))
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/util.py", line 96, in get_type_name
    return _(u'Integer number')
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 545, in validate_mapping
    raise err_type(provided=get_type_name(type(d)))
good.schema.errors.Invalid: Wrong value type: expected Dictionary, got String
>>> s({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 653, in validate_mapping
    raise MultipleInvalid.if_multiple(errors)
good.schema.errors.Invalid: Wrong value type: expected Dictionary, got String
>>> s({1:1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 653, in validate_mapping
    raise MultipleInvalid.if_multiple(errors)
good.schema.errors.MultipleInvalid: Wrong value type: expected Dictionary, got String
>>> s({"d":1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 653, in validate_mapping
    raise MultipleInvalid.if_multiple(errors)
good.schema.errors.MultipleInvalid: Wrong value type: expected Dictionary, got String
>>> s({"d":"meow"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 653, in validate_mapping
    raise MultipleInvalid.if_multiple(errors)
good.schema.errors.MultipleInvalid: Wrong value type: expected Dictionary, got String
>>> 
>>> 
>>> 
>>> 
>>> 
>>> s = Schema({"a": str})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 280, in __init__
    extra_keys)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 502, in _compile_mapping
    for key, value in schema.items()}
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 502, in <dictcomp>
    for key, value in schema.items()}
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 189, in sub_compile
    matcher
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 304, in _compile_type
    err_type = self.Invalid(_(u'Wrong type'), self.name)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 545, in validate_mapping
    raise err_type(provided=get_type_name(type(d)))
good.schema.errors.Invalid: Wrong value type: expected Dictionary, got String
>>> s = Schema({"a": str})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 280, in __init__
    extra_keys)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 502, in _compile_mapping
    for key, value in schema.items()}
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 502, in <dictcomp>
    for key, value in schema.items()}
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 189, in sub_compile
    matcher
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 304, in _compile_type
    err_type = self.Invalid(_(u'Wrong type'), self.name)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 545, in validate_mapping
    raise err_type(provided=get_type_name(type(d)))
good.schema.errors.Invalid: Wrong value type: expected Dictionary, got String
>>> s
CompiledSchema({'a': <type 'str'>}, [], Required, Reject)
>>> del s
>>> s = Schema({"a": str})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 280, in __init__
    extra_keys)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 502, in _compile_mapping
    for key, value in schema.items()}
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 502, in <dictcomp>
    for key, value in schema.items()}
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 189, in sub_compile
    matcher
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 304, in _compile_type
    err_type = self.Invalid(_(u'Wrong type'), self.name)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 545, in validate_mapping
    raise err_type(provided=get_type_name(type(d)))
good.schema.errors.Invalid: Wrong value type: expected Dictionary, got String
>>> s = Schema({"b": str})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 280, in __init__
    extra_keys)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 502, in _compile_mapping
    for key, value in schema.items()}
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 502, in <dictcomp>
    for key, value in schema.items()}
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 189, in sub_compile
    matcher
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 304, in _compile_type
    err_type = self.Invalid(_(u'Wrong type'), self.name)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/__init__.py", line 302, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 63, in __call__
    return self.compiled(value)
  File "/home/dpn/.virtualenvs/inboxapi/local/lib/python2.7/site-packages/good/schema/compiler.py", line 545, in validate_mapping
    raise err_type(provided=get_type_name(type(d)))
good.schema.errors.Invalid: Wrong value type: expected Dictionary, got String
>>> Schema
<class 'good.schema.Schema'>
>>> 
```

**Comment by kolypto** [comment]
Yes, I can only say that ipython messes up gettext's underscore function. I believe this is already fixed in the most recent ipython.
