### ISSUE TITLE
Can't create more than one Schema

### ISSUE THREAD

**Issue by derrley** [kolypto/py-good#5]
```
>>> import good
>>> good.Schema(int)(1)
1
>>> good.Schema(int)(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/good/schema/__init__.py", line 280, in __init__
    extra_keys)
  File "/Library/Python/2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/Library/Python/2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/Library/Python/2.7/site-packages/good/schema/compiler.py", line 301, in _compile_type
    self.name = get_type_name(schema)
  File "/Library/Python/2.7/site-packages/good/schema/util.py", line 96, in get_type_name
    return _(u'Integer number')
TypeError: 'int' object is not callable
>>> reload(good)
<module 'good' from '/Library/Python/2.7/site-packages/good/__init__.pyc'>
>>> good.Schema(int)(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/good/schema/__init__.py", line 280, in __init__
    extra_keys)
  File "/Library/Python/2.7/site-packages/good/schema/compiler.py", line 46, in __init__
    self.compiled = self.compile_schema(self.schema)
  File "/Library/Python/2.7/site-packages/good/schema/compiler.py", line 264, in compile_schema
    return compiler(schema)
  File "/Library/Python/2.7/site-packages/good/schema/compiler.py", line 301, in _compile_type
    self.name = get_type_name(schema)
  File "/Library/Python/2.7/site-packages/good/schema/util.py", line 96, in get_type_name
    return _(u'Integer number')
TypeError: 'module' object is not callable
>>>
```

I've tried in all versions of python, mac and linux. It seems like you're holding on to some module-level state somewhere, and even reload() doesn't blow it away. I've done a cursory glance over the code, but I didn't find anything.

I love what you've done with performance, but I can't adopt the library with a bug like this.

**Comment by kolypto** [comment]
Duplicate #3: ipython messes up gettext's underscore function. Update your ipython.
